# Generated by Django 4.1.3 on 2022-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMascota', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=40)),
                ('castracion', models.CharField(max_length=40)),
                ('nombreTutelar', models.CharField(max_length=40)),
                ('telefono', models.IntegerField()),
                ('mail', models.EmailField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
