# Generated by Django 4.1.3 on 2022-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontrados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRetiene', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Provisorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProvisorio', models.CharField(max_length=40)),
                ('tipo', models.IntegerField()),
                ('genero', models.CharField(max_length=40)),
                ('animalesenCasa', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='adopcion',
            name='tipo',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
