# Generated by Django 4.1.3 on 2022-12-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_encontrados_provisorios_adopcion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopcion',
            name='edad',
            field=models.FloatField(),
        ),
    ]
